### ISSUE TITLE
Jetpack Photon images with query string parameters does not convert into image

### ISSUE THREAD

**Issue by agk4444** [recrypto/wp-steem#1]
When a post contains a Jetpack Photon images with query string parameters the markdown may need to remove those extra params to make the images work
For example
[https://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2017/06/13/a6fcca8fa125fd937025dd471e000b38.jpg?crop=0%20px,30,1097%20px,617.0625%20px ]
**Does not show an Image

while**

[https://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2017/06/13/a6fcca8fa125fd937025dd471e000b38.jpg ]

**does.**

**Comment by recrypto** [comment]
Can you please link me to the Steem post that this image is included? Thanks!

**Comment by agk4444** [comment]
Here u go https://steemit.com/trumpnafta/@socialnewsxyz/trump-administration-unveils-nafta-renegotiating-goals.  Thanks for the plugin again. I fixed the post by removing extra parameters.


Gopi

**Comment by recrypto** [comment]
Thanks for that. You're welcome! :)

The Markdown format conversion seems to be okay. I'm thinking this is the side of Steemit or any platform that converts Markdown format to HTML format that somehow breaks because of those query parameters. Still investigating the issue.
