### ISSUE TITLE
Not Working - Debug Logs - How do I troubleshoot.

### ISSUE THREAD

**Issue by ryanherbison** [recrypto/wp-steem#2]
Is there any sort of debug options, nothing happens when I do the post even after checking publish on steem blockchain and adding tags.  I've confirmed my keys and username.  Is there someplace that I can look for a log.  So far I see nothing in apache access/error logs or php but I have not dug that deep.  Would I expect to see any output when making a post.

Thanks

**Comment by recrypto** [comment]
Hello, I'm currently in the works of adding intuitive messages when doing an action. As of this moment, there is currently no way of showing it. No worries, this will be added in the next version very soon.

**Comment by recrypto** [comment]
Able to include this enhancement on Version 1.0.3 of the plugin. See https://github.com/recrypto/wp-steem/commit/7ca9dc1e05a9591c3bf67b41214e1195beb619ab
