### ISSUE TITLE
SteemConnect Support

### ISSUE THREAD

**Issue by inertia186** [recrypto/wp-steem#5]
Some people were wondering if you could add SteemConnect urls to the final check-out screen so they don't have to copy/paste the memo.  E.g.:

```
https://v2.steemconnect.com/sign/transfer?to=youraccount&from=theiraccount&amount=1.000%20SBD&memo=the%20memo
```

**Comment by inertia186** [comment]
Note, I created this issue not realizing there was `woocommerce-steem`.  As it turns out, `woocommerce-steem` was the plug-in these people were actually using.

**Comment by recrypto** [comment]
As for that, I'll check and consider that on the next update for WooCommerce Steem plugin.
