### ISSUE TITLE
Help: The plugin is posting drafts 

### ISSUE THREAD

**Issue by andretg79** [recrypto/wp-steem#7]
Hi there,

This is a great plugin. I have been testing it out and it works great.

The only thing I cannot figure out is how to stop it from publishing draft wordpress posts to steemit.

I only want it to publish to steemit once I have published on wordpress. Is there a way to do this?

Thank you

**Comment by recrypto** [comment]
Hello,

Can you please upload the newest version of the plugin which is version 1.0.4? I've made a fix just for this. Please let me know your thoughts. Thanks and greatly appreciate it! :)

**Comment by recrypto** [comment]
Patch fix is found on this commit:
https://github.com/recrypto/wp-steem/commit/36b37629ca330f533ee1b0b8d0830f73d3c0adf2
