### ISSUE TITLE
Silently failing as of WP 4.8.2

### ISSUE THREAD

**Issue by smcnally** [recrypto/wp-steem#8]
wp-steem is no longer working as of a WP core update to 4.8.2.

Not getting errors in the admin UI. 
No errors in apache error.log. 
The WP post is updated as designed, but there's no sign of items published or drafts in steemit.

**Comment by hifarrer** [comment]
Yup, having same issue here.

**Comment by mahendrabvala** [comment]
For me the same, I am getting 

> Please wait for 300 seconds to be able to publish this post to the Steem blockchain as there is a 5 minute cooldown.

and then nothing, Post is published sucssessfully on WP but not published on stemmit.

**Comment by recrypto** [comment]
Hello guys,

Sorry for this issue. Operation should be back to normal now. I apologize for this outage.

**Comment by hifarrer** [comment]
it works! Thank you!
There is also a minor bug, the post gets published to steem even when you "save as draft", not a big deal I think but I thought you should know. Thanks again.
